version: '3'
services:
  requirement-classifier:
    image: req-classifier
    ports:
     - "9402:9402"
     - "9403:9403"
     - "8080:8080"
  integration-service:
    image: "is"
    ports:
     - "5000:5000"
    volumes:
     - ./app:/app/src